apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce

resources:
  - namespace.yaml
  - postgresql.yaml
  - minio.yaml
  - chromadb.yaml
  - kafka-consumer.yaml
  - kafka-aggregator.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - vault/config.yaml
  - vault/vault.yaml
  - vault/bootstrap-job.yaml
  - vault/secretstore.yaml
  - vault/external-secrets.yaml
  - hpa.yaml

images:
  - name: backend
    newName: ecommerce-backend
    newTag: latest
  - name: frontend
    newName: ecommerce-frontend
    newTag: latest
