---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/ecommerce/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/ecommerce/postgres
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: secret/data/ecommerce/minio
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: secret/data/ecommerce/minio
        property: secret-key
