apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce

resources:
  - loki.yaml
  - fluentd.yaml
  - prometheus.yaml
  - grafana.yaml
  - grafana-dashboards.yaml
  - alertmanager.yaml
